-- MySQL Script generated by MySQL Workbench
-- Thu Feb 23 11:50:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clinicapi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinicapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinicapi` DEFAULT CHARACTER SET utf8 ;
USE `clinicapi` ;

-- -----------------------------------------------------
-- Table `clinicapi`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicapi`.`usuario` (
  `id` INT(11) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `perfil` INT(11) NOT NULL,
  `admin` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clinicapi`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicapi`.`medico` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `sobrenome` VARCHAR(50) NOT NULL,
  `cpf` BIGINT(20) NOT NULL,
  `crm` VARCHAR(30) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC),
  CONSTRAINT `medico_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `clinicapi`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clinicapi`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicapi`.`paciente` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` BIGINT(20) NOT NULL,
  `telefone` BIGINT(20) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clinicapi`.`agenda_medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicapi`.`agenda_medico` (
  `id` INT(11) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `medico_id_medico` INT(11) NOT NULL,
  `Paciente_id_paciente` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `medico_id_medico` (`medico_id_medico` ASC),
  INDEX `Paciente_id_paciente` (`Paciente_id_paciente` ASC),
  CONSTRAINT `agenda_medico_ibfk_1`
    FOREIGN KEY (`medico_id_medico`)
    REFERENCES `clinicapi`.`medico` (`id`),
  CONSTRAINT `agenda_medico_ibfk_2`
    FOREIGN KEY (`Paciente_id_paciente`)
    REFERENCES `clinicapi`.`paciente` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clinicapi`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicapi`.`medicamento` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tarja` VARCHAR(45) NOT NULL,
  `formula` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clinicapi`.`secretaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicapi`.`secretaria` (
  `id` INT(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` BIGINT(20) NOT NULL,
  `telefone` BIGINT(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usuario_idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_idusuario` (`usuario_idusuario` ASC),
  CONSTRAINT `secretaria_ibfk_1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `clinicapi`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clinicapi`.`prontuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicapi`.`prontuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `observacao` VARCHAR(300) NOT NULL,
  `medico_id_medico` INT(11) NOT NULL,
  `paciente_id_paciente` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `medico_id_medico`, `paciente_id_paciente`),
  INDEX `fk_prontoario_medico1_idx` (`medico_id_medico` ASC),
  INDEX `fk_prontoario_paciente1_idx` (`paciente_id_paciente` ASC),
  CONSTRAINT `fk_prontoario_medico1`
    FOREIGN KEY (`medico_id_medico`)
    REFERENCES `clinicapi`.`medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prontoario_paciente1`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `clinicapi`.`paciente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinicapi`.`medicamento_has_prontoario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicapi`.`medicamento_has_prontoario` (
  `medicamento_id_medicamento` INT(11) NOT NULL,
  `prontoario_idprontoario` INT NOT NULL,
  PRIMARY KEY (`medicamento_id_medicamento`, `prontoario_idprontoario`),
  INDEX `fk_medicamento_has_prontoario_prontoario1_idx` (`prontoario_idprontoario` ASC),
  INDEX `fk_medicamento_has_prontoario_medicamento1_idx` (`medicamento_id_medicamento` ASC),
  CONSTRAINT `fk_medicamento_has_prontoario_medicamento1`
    FOREIGN KEY (`medicamento_id_medicamento`)
    REFERENCES `clinicapi`.`medicamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_has_prontoario_prontoario1`
    FOREIGN KEY (`prontoario_idprontoario`)
    REFERENCES `clinicapi`.`prontuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
